### ISSUE TITLE
nothing drops when stone is broken with T-Construct or ProjectE pickaxes'

### ISSUE THREAD

**Issue by mindcloud69** [Conquest-Reforged/ConquestReforged#20]
nothing drops when stone variants are broken with T-Construct or ProjectE pickaxes in survival. 

- Works when Conquest is disabled. 
- Regular Minecraft pickaxes work correctly.
- Non-stone blocks drops work correctly with modded pickaxes.
- Other blocks all seem to work with modded tools.

One thing I noticed is that the file blocks\BlockStonesMeta\stone_rocks_1.conf
has the line "tool: axe" instead of pickaxe. I tried changing it but it gets overwritten on start. 

I tried trying with T-con disabled and then with ProjectE disabled. i made no difference cobble still did not drop from stone.

mods
MC 1.12.2
Forge 14.23.2.2624
ConquestReforged-3.0.0-mc1.12.2.jar
Mantle-1.12-1.3.1.21.jar
ProjectE-1.12-PE1.2.0.jar
TConstruct-1.12.2-2.9.1.65.jar
jei_1.12.2-4.8.5.159.jar
it doesn't matter if optifine is installed happens with or without it.

[fml-client-1.log](https://gist.github.com/mindcloud69/d7805572d36537a82628fe917b74dbe9)

**Comment by HIPPOKLEIDES** [comment]
stone_rocks_1 was set to be broken by axes by mistake, so I just fixed that. Are blocks such as stone_full_1 working correctly with modded pickaxes?

**Comment by True-Sebastos** [comment]
Unfortunately this issue is not yet resolved. At least not for me.

Currently playing a 1.12.2 custom pack with the latest Conquest Reforged version (3.0.2) and the latest Tinkers Construct (2.12.0.115). Everything OP said is still applicable like:

* Works when Conquest is disabled.

* Regular Minecraft pickaxes work correctly. _Conquest ones do as well._

* Non-stone blocks drops work correctly with modded pickaxes.

* Other blocks all seem to work with modded tools.

Is there any way to fix it? It is kinda useful regarding stone itself, saves me from making a /dank/null ;) But I am scared to break stone stuff with my tinkers pick fearing it won't drop anything.

**Comment by ToxicCosmos** [comment]
I'm having the same issue. I'm playing Enigmatica 2 (1.12.2).
